### ISSUE TITLE
Azure Sql Database error NXDOMAIN

### ISSUE THREAD

**Issue by zerobatu** [elixir-ecto/tds#140]
Last week I lost the connection with my Azure Sql Database, some week ago was working, I did't change in the connection params and I did't change the library version.

Error:
```
10:54:38.699 [error] GenServer #PID<0.440.0> terminating
** (CaseClauseError) no case clause matching: {:error, %Tds.Error{message: "tcp connect: nxdomain", mssql: nil}}
    (tds 2.3.1) lib/tds/protocol.ex:483: Tds.Protocol.decode/2
    (tds 2.3.1) lib/tds/protocol.ex:530: Tds.Protocol.login/1
    (tds 2.3.1) lib/tds/protocol.ex:369: Tds.Protocol.connect/2
    (db_connection 2.4.2) lib/db_connection/connection.ex:82: DBConnection.Connection.connect/2
    (connection 1.1.0) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib 3.15) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: nil
State: Tds.Protocol
```

Elixir code
```
defmodule SqlTestConnection do
  def check() do
    params = [
      database: "****",
      username: "****",
      password: "****",
      hostname: "****.database.windows.net",
      ssl: :required,
      show_sensitive_data_on_connection_error: true,
      port: 1433
    ]

    {:ok, pid} = Tds.start_link(params)

    Tds.query!(pid, "SELECT @@version", [])
  end
end
```

I tested the connection with nodejs

```
$ cat main.js

var Connection = require('tedious').Connection;
var Request = require('tedious').Request;

var config = {
    server: "****.database.windows.net",
    authentication: {
        type: 'default',
        options: {
            userName: "****",
            password: "****"
        }
    },
    options: {
        encrypt: true,
        database: "****"
    }
};

var connection = new Connection(config);
connection.on('connect', function(err) {
  if(err) {
    console.log(err);
  } else {
    console.log("Connected");

    request = new Request("select @@version", function(err, rowCount) {
      if (err) {
        console.log(err);
      } else {
        console.log(rowCount + ' rows');
      }
    });

    request.on('row', function(columns) {
      columns.forEach(function(column) {
        console.log(column.value);
      });
    });

    connection.execSql(request);
  }
});

connection.connect();

## In nodejs it's working

$ node main.js
Connected
Microsoft SQL Azure (RTM) - 12.0.2000.8
	Aug 10 2022 15:14:09
	Copyright (C) 2022 Microsoft Corporation

1 rows
```

Network tests
```
$ ping ****.database.windows.net
PING ****.privatelink.database.windows.net (10.236.100.92): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2

--- ****.privatelink.database.windows.net ping statistics ---
4 packets transmitted, 0 packets received, 100.0% packet loss

## this servers not accept ping 

$ telnet ****.database.windows.net 1433
Trying 10.236.100.92...
Connected to ****.privatelink.database.windows.net.
Escape character is '^]'.

## The url accept tcp connection
```

I check the DNS
```
$ nslookup ****.database.windows.net
;; Got recursion not available from 172.29.199.9, trying next server
Server:		172.29.199.12
Address:	172.29.199.12#53

Non-authoritative answer:
****.database.windows.net	canonical name = ****.privatelink.database.windows.net.
Name:	****.privatelink.database.windows.net
Address: xx.xxx.xxx.xx
```

TDS version:
```
  "tds": {:hex, :tds, "2.3.1", "80b371d358065becea3b28f5fdcb4d7c67b6624658b2c46c066092eb774872fc", [:mix], [{:db_connection, "~> 2.0", [hex: :db_connection, repo: "hexpm", optional: false]}, {:decimal, "~> 1.9 or ~> 2.0", [hex: :decimal, repo: "hexpm", optional: false]}, {:jason, "~> 1.0", [hex: :jason, repo: "hexpm", optional: true]}], "hexpm", "74f53e25e043263526d47e4249ec5290323e249761acb4f80f5eb43350935c56"},
```

I hope you can help

Thanks

**Comment by zerobatu** [comment]
issue solved https://github.com/elixir-ecto/tds/pull/141
